// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserAuthService drives a real Chromium browser so the user can log into
 * Yandex interactively, then harvests the resulting cookies (including the
 * HttpOnly auth cookies that page scripts cannot read) via the DevTools
 * protocol and returns them in Netscape format.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Login opens a browser window pointed at the Yandex login page and waits until
 * the user authenticates, then returns the captured cookies. When proxy is a
 * non-empty proxy URL, browser traffic is routed through a local relay so that
 * authenticated proxies work despite Chromium's inability to pass credentials
 * on the command line.
 * 
 * The ctx is supplied by Wails and is cancelled when the frontend cancels the
 * call's CancellablePromise; cancelling tears down the browser process.
 */
export function Login(proxy: string): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(1920162496, proxy).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LoginResult.createFrom;
