// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddAccountToConfig(account: $models.Account): $CancellablePromise<void> {
    return $Call.ByID(1520924950, account);
}

export function GetConfig($0: {}): $CancellablePromise<$models.GlobalSettings> {
    return $Call.ByID(2320765359, $0).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveAccountFromConfig(target_account: $models.Account): $CancellablePromise<void> {
    return $Call.ByID(4242096952, target_account);
}

// Private type creation functions
const $$createType0 = $models.GlobalSettings.createFrom;
