// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddAccountToConfig(account: $models.Account): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1520924950, account) as any;
    return $resultPromise;
}

export function GetConfig($0: {}): Promise<$models.GlobalSettings> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2320765359, $0) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RemoveAccountFromConfig(target_account: $models.Account): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4242096952, target_account) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.GlobalSettings.createFrom;
