// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * YaApiService handles interactions with the rewards API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClaimDailyCoins reads the current daily plan and claims it only when available.
 */
export function ClaimDailyCoins(account: $models.Account | null): $CancellablePromise<string> {
    return $Call.ByID(935410992, account);
}

/**
 * ClaimGameRewards discovers current GamesHub games, submits their current
 * maximum result, and claims any achieved legacy reward levels. New games are
 * picked up from the server response without code changes.
 */
export function ClaimGameRewards(account: $models.Account | null): $CancellablePromise<string> {
    return $Call.ByID(2280127061, account);
}

/**
 * GetRewardsJson retrieves current prizes, login, and coin balance.
 */
export function GetRewardsJson(account: $models.Account | null): $CancellablePromise<[string, string, string]> {
    return $Call.ByID(1882876837, account);
}

/**
 * Roll executes a spin using the active AppHost endpoint.
 */
export function Roll(account: $models.Account | null): $CancellablePromise<string> {
    return $Call.ByID(3671417624, account);
}
